_listing:
	@printf "${BLU}{{justfile()}}${NOC}\n"
	@just --unsorted --list --list-heading='' --list-prefix=' • ' \
		| grep -v 'alias for'

compile: clean
	go install -v

clean:
	rm -rf /dev/shm/cbzr2pdf*

set shell := ["bash","-uc"]
# vim: ft=make
